spring.application.name=messagehub

server.port=5000

spring.datasource.url=jdbc:mysql://localhost:3306/messagehub?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Harshgupta3034@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JWT
messagehub.jwt.secret=messagehub_super_secret_change_this_123456789